import type { Metadata } from 'next';
import React from 'react';
import './globals.css';
import Layout from '@/shared/ui/Layout';
import { Header } from '@/widgets/header';
import { Footer } from '@/widgets/footer';
import AppProviders from './providers/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>
          <Layout headerSlot={<Header />} footerSlot={<Footer />}>
            {children}
          </Layout>
        </AppProviders>
      </body>
    </html>
  );
}
